# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: robot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='robot.proto',
  package='robot',
  syntax='proto3',
  serialized_pb=_b('\n\x0brobot.proto\x12\x05robot\"\x07\n\x05\x45mpty\"\xa3\x01\n\x0f\x45nvironmentInfo\x12\n\n\x02Id\x18\x01 \x01(\x04\x12\x17\n\x0f\x45nvironmentTemp\x18\x02 \x01(\x02\x12\x1a\n\x12\x41tmospherePressure\x18\x03 \x01(\x03\x12\x10\n\x08\x41ltitude\x18\x04 \x01(\x02\x12\x10\n\x08Humidity\x18\x05 \x01(\r\x12\x17\n\x0fRobotBatteryLvl\x18\x06 \x01(\r\x12\x12\n\nBrightness\x18\x07 \x01(\r\"^\n\x0eHumanHeartInfo\x12\n\n\x02Id\x18\x01 \x01(\x04\x12\x11\n\tHeartRate\x18\x02 \x01(\r\x12\x13\n\x0bHeartRhythm\x18\x03 \x01(\x02\x12\x18\n\x10\x44\x65viceBatteryLvl\x18\x04 \x01(\r\"=\n\x0fHumanCommonInfo\x12\n\n\x02Id\x18\x01 \x01(\x04\x12\x10\n\x08Humidity\x18\x02 \x01(\r\x12\x0c\n\x04Temp\x18\x03 \x01(\x02\"3\n\rFlowerpotInfo\x12\x10\n\x08PouredOn\x18\x01 \x01(\x08\x12\x10\n\x08Humidity\x18\x02 \x01(\r2\x80\x02\n\x0cRobotService\x12<\n\x12PutEnvironmentInfo\x12\x16.robot.EnvironmentInfo\x1a\x0c.robot.Empty\"\x00\x12:\n\x11PutHumanHeartInfo\x12\x15.robot.HumanHeartInfo\x1a\x0c.robot.Empty\"\x00\x12<\n\x12PutHumanCommonInfo\x12\x16.robot.HumanCommonInfo\x1a\x0c.robot.Empty\"\x00\x12\x38\n\x10PutFlowerpotInfo\x12\x14.robot.FlowerpotInfo\x1a\x0c.robot.Empty\"\x00\x42\x32Z0github.com/evgeniy-scherbina/hard_and_soft/robotb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='robot.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=29,
)


_ENVIRONMENTINFO = _descriptor.Descriptor(
  name='EnvironmentInfo',
  full_name='robot.EnvironmentInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='robot.EnvironmentInfo.Id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='EnvironmentTemp', full_name='robot.EnvironmentInfo.EnvironmentTemp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='AtmospherePressure', full_name='robot.EnvironmentInfo.AtmospherePressure', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Altitude', full_name='robot.EnvironmentInfo.Altitude', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Humidity', full_name='robot.EnvironmentInfo.Humidity', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='RobotBatteryLvl', full_name='robot.EnvironmentInfo.RobotBatteryLvl', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Brightness', full_name='robot.EnvironmentInfo.Brightness', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=195,
)


_HUMANHEARTINFO = _descriptor.Descriptor(
  name='HumanHeartInfo',
  full_name='robot.HumanHeartInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='robot.HumanHeartInfo.Id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HeartRate', full_name='robot.HumanHeartInfo.HeartRate', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='HeartRhythm', full_name='robot.HumanHeartInfo.HeartRhythm', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='DeviceBatteryLvl', full_name='robot.HumanHeartInfo.DeviceBatteryLvl', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=291,
)


_HUMANCOMMONINFO = _descriptor.Descriptor(
  name='HumanCommonInfo',
  full_name='robot.HumanCommonInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='robot.HumanCommonInfo.Id', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Humidity', full_name='robot.HumanCommonInfo.Humidity', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Temp', full_name='robot.HumanCommonInfo.Temp', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=354,
)


_FLOWERPOTINFO = _descriptor.Descriptor(
  name='FlowerpotInfo',
  full_name='robot.FlowerpotInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PouredOn', full_name='robot.FlowerpotInfo.PouredOn', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='Humidity', full_name='robot.FlowerpotInfo.Humidity', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=356,
  serialized_end=407,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['EnvironmentInfo'] = _ENVIRONMENTINFO
DESCRIPTOR.message_types_by_name['HumanHeartInfo'] = _HUMANHEARTINFO
DESCRIPTOR.message_types_by_name['HumanCommonInfo'] = _HUMANCOMMONINFO
DESCRIPTOR.message_types_by_name['FlowerpotInfo'] = _FLOWERPOTINFO

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'robot_pb2'
  # @@protoc_insertion_point(class_scope:robot.Empty)
  ))
_sym_db.RegisterMessage(Empty)

EnvironmentInfo = _reflection.GeneratedProtocolMessageType('EnvironmentInfo', (_message.Message,), dict(
  DESCRIPTOR = _ENVIRONMENTINFO,
  __module__ = 'robot_pb2'
  # @@protoc_insertion_point(class_scope:robot.EnvironmentInfo)
  ))
_sym_db.RegisterMessage(EnvironmentInfo)

HumanHeartInfo = _reflection.GeneratedProtocolMessageType('HumanHeartInfo', (_message.Message,), dict(
  DESCRIPTOR = _HUMANHEARTINFO,
  __module__ = 'robot_pb2'
  # @@protoc_insertion_point(class_scope:robot.HumanHeartInfo)
  ))
_sym_db.RegisterMessage(HumanHeartInfo)

HumanCommonInfo = _reflection.GeneratedProtocolMessageType('HumanCommonInfo', (_message.Message,), dict(
  DESCRIPTOR = _HUMANCOMMONINFO,
  __module__ = 'robot_pb2'
  # @@protoc_insertion_point(class_scope:robot.HumanCommonInfo)
  ))
_sym_db.RegisterMessage(HumanCommonInfo)

FlowerpotInfo = _reflection.GeneratedProtocolMessageType('FlowerpotInfo', (_message.Message,), dict(
  DESCRIPTOR = _FLOWERPOTINFO,
  __module__ = 'robot_pb2'
  # @@protoc_insertion_point(class_scope:robot.FlowerpotInfo)
  ))
_sym_db.RegisterMessage(FlowerpotInfo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z0github.com/evgeniy-scherbina/hard_and_soft/robot'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces


  class RobotServiceStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.PutEnvironmentInfo = channel.unary_unary(
          '/robot.RobotService/PutEnvironmentInfo',
          request_serializer=EnvironmentInfo.SerializeToString,
          response_deserializer=Empty.FromString,
          )
      self.PutHumanHeartInfo = channel.unary_unary(
          '/robot.RobotService/PutHumanHeartInfo',
          request_serializer=HumanHeartInfo.SerializeToString,
          response_deserializer=Empty.FromString,
          )
      self.PutHumanCommonInfo = channel.unary_unary(
          '/robot.RobotService/PutHumanCommonInfo',
          request_serializer=HumanCommonInfo.SerializeToString,
          response_deserializer=Empty.FromString,
          )
      self.PutFlowerpotInfo = channel.unary_unary(
          '/robot.RobotService/PutFlowerpotInfo',
          request_serializer=FlowerpotInfo.SerializeToString,
          response_deserializer=Empty.FromString,
          )


  class RobotServiceServicer(object):

    def PutEnvironmentInfo(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def PutHumanHeartInfo(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def PutHumanCommonInfo(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def PutFlowerpotInfo(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_RobotServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'PutEnvironmentInfo': grpc.unary_unary_rpc_method_handler(
            servicer.PutEnvironmentInfo,
            request_deserializer=EnvironmentInfo.FromString,
            response_serializer=Empty.SerializeToString,
        ),
        'PutHumanHeartInfo': grpc.unary_unary_rpc_method_handler(
            servicer.PutHumanHeartInfo,
            request_deserializer=HumanHeartInfo.FromString,
            response_serializer=Empty.SerializeToString,
        ),
        'PutHumanCommonInfo': grpc.unary_unary_rpc_method_handler(
            servicer.PutHumanCommonInfo,
            request_deserializer=HumanCommonInfo.FromString,
            response_serializer=Empty.SerializeToString,
        ),
        'PutFlowerpotInfo': grpc.unary_unary_rpc_method_handler(
            servicer.PutFlowerpotInfo,
            request_deserializer=FlowerpotInfo.FromString,
            response_serializer=Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'robot.RobotService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaRobotServiceServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def PutEnvironmentInfo(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def PutHumanHeartInfo(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def PutHumanCommonInfo(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def PutFlowerpotInfo(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaRobotServiceStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def PutEnvironmentInfo(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    PutEnvironmentInfo.future = None
    def PutHumanHeartInfo(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    PutHumanHeartInfo.future = None
    def PutHumanCommonInfo(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    PutHumanCommonInfo.future = None
    def PutFlowerpotInfo(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    PutFlowerpotInfo.future = None


  def beta_create_RobotService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('robot.RobotService', 'PutEnvironmentInfo'): EnvironmentInfo.FromString,
      ('robot.RobotService', 'PutFlowerpotInfo'): FlowerpotInfo.FromString,
      ('robot.RobotService', 'PutHumanCommonInfo'): HumanCommonInfo.FromString,
      ('robot.RobotService', 'PutHumanHeartInfo'): HumanHeartInfo.FromString,
    }
    response_serializers = {
      ('robot.RobotService', 'PutEnvironmentInfo'): Empty.SerializeToString,
      ('robot.RobotService', 'PutFlowerpotInfo'): Empty.SerializeToString,
      ('robot.RobotService', 'PutHumanCommonInfo'): Empty.SerializeToString,
      ('robot.RobotService', 'PutHumanHeartInfo'): Empty.SerializeToString,
    }
    method_implementations = {
      ('robot.RobotService', 'PutEnvironmentInfo'): face_utilities.unary_unary_inline(servicer.PutEnvironmentInfo),
      ('robot.RobotService', 'PutFlowerpotInfo'): face_utilities.unary_unary_inline(servicer.PutFlowerpotInfo),
      ('robot.RobotService', 'PutHumanCommonInfo'): face_utilities.unary_unary_inline(servicer.PutHumanCommonInfo),
      ('robot.RobotService', 'PutHumanHeartInfo'): face_utilities.unary_unary_inline(servicer.PutHumanHeartInfo),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_RobotService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('robot.RobotService', 'PutEnvironmentInfo'): EnvironmentInfo.SerializeToString,
      ('robot.RobotService', 'PutFlowerpotInfo'): FlowerpotInfo.SerializeToString,
      ('robot.RobotService', 'PutHumanCommonInfo'): HumanCommonInfo.SerializeToString,
      ('robot.RobotService', 'PutHumanHeartInfo'): HumanHeartInfo.SerializeToString,
    }
    response_deserializers = {
      ('robot.RobotService', 'PutEnvironmentInfo'): Empty.FromString,
      ('robot.RobotService', 'PutFlowerpotInfo'): Empty.FromString,
      ('robot.RobotService', 'PutHumanCommonInfo'): Empty.FromString,
      ('robot.RobotService', 'PutHumanHeartInfo'): Empty.FromString,
    }
    cardinalities = {
      'PutEnvironmentInfo': cardinality.Cardinality.UNARY_UNARY,
      'PutFlowerpotInfo': cardinality.Cardinality.UNARY_UNARY,
      'PutHumanCommonInfo': cardinality.Cardinality.UNARY_UNARY,
      'PutHumanHeartInfo': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'robot.RobotService', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
